[package]
name = "chip8rs"
version = "0.1.0"
authors = ["uma0317 <blog3170@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "*"
rand = "0.6"
termion = "1.5.3"
env_logger = "0.7.1"
rodio = "0.9.0"